apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gin-skeleton.fullname" . }}
  labels:
    {{- include "gin-skeleton.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
